name: Continous integration

on:
  workflow_dispatch:
  pull_request:
    # only PR for master
    branches:
      - master
      - next
      - vNext

jobs:
  continous_integration:
    runs-on: macOS-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: NodeJS setup
        uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Installing dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test+coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
